"""Initial migration

Revision ID: 69ebb1f27825
Revises: 
Create Date: 2025-11-23 00:43:54.005380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69ebb1f27825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_items', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('overdue', 'due_soon', 'scheduled', 'in_progress', 'completed', 'cancelled', name='maintenancestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='maintenancepriority'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
        batch_op.alter_column('parts_needed',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_due_date'))
        batch_op.drop_index(batch_op.f('idx_priority'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_vehicle_id'))
        batch_op.create_index(batch_op.f('ix_maintenance_items_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_items_vehicle_id'))
        batch_op.create_index(batch_op.f('idx_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('attachments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('parts_needed',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='maintenancepriority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.Enum('overdue', 'due_soon', 'scheduled', 'in_progress', 'completed', 'cancelled', name='maintenancestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))

    # ### end Alembic commands ###
